# This file was generated by GoReleaser. DO NOT EDIT.
cask "repokeeper" do
  name "repokeeper"
  desc "Track and manage many Git repositories from a single config"
  homepage "https://github.com/skaphos/repokeeper"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repokeeper"

  on_macos do
    on_intel do
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_darwin_amd64.tar.gz"
      sha256 "fac2fc23c11cb93f40fbf6f5c18c79ac048cff02e93aadf0411778fe97e330eb"
    end
    on_arm do
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_darwin_arm64.tar.gz"
      sha256 "632a8b8d8c05f6bad9166b9f855422fa424c8ebee08ea4a99be60a3b675f4219"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_linux_amd64.tar.gz"
      sha256 "d5fa26cb093e0ec95b2c2d77d9a5c8260e6117352c03b622b673e8270250f6af"
    end
    on_arm do
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_linux_arm64.tar.gz"
      sha256 "bd25bc574e69e07a0aee6ee6953a4a2e4e09f74e10a30f45ff97b6f50483a8c6"
    end
  end

  # No zap stanza required
end
