# This file was generated by GoReleaser. DO NOT EDIT.
cask "repokeeper" do
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/repokeeper"]
    end
  end

  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "4434e53826470377f7e43f2dda6a25dc5de0b5f7db82b5571597603ade31d897"
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ebbc3a32187b82d91e7c470715925fc2653e6cc20a6dcb306336130dab3ff103"
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ffecbf12d2e8f66fb6c7b5c59cf65bd5cbd481ad7e79109b521d909c854ab52"
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "009a5af5f51358b4bd209992bf08127307b49423858138e9b0ab56fddb99a261"
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repokeeper"
  desc "Track and manage many Git repositories from a single config"
  homepage "https://github.com/skaphos/repokeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repokeeper"

  # No zap stanza required

end
