# This file was generated by GoReleaser. DO NOT EDIT.
cask "repokeeper" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/repokeeper"]
  end

  version "0.7.1"

  on_macos do
    on_intel do
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_darwin_amd64.tar.gz"
      sha256 "9e5b92fd564c6c1f3fd0cf34814d678de169faa576c5d46016544bb62622b021"
    end
    on_arm do
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_darwin_arm64.tar.gz"
      sha256 "8296c36a24ef3e9f5d91867c3fc8d3967f3b0456cefd719917d833173a3a44bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_linux_amd64.tar.gz"
      sha256 "fac67ee21587da62e5eb8d06b702c221ea4a23e9ebc63f801620068346f13236"
    end
    on_arm do
      url "https://github.com/skaphos/repokeeper/releases/download/v#{version}/repokeeper_#{version}_linux_arm64.tar.gz"
      sha256 "631de049941b50874c2a53039590c3bfa42823b4508eda78a7eca57cf51c21cf"
    end
  end

  name "repokeeper"
  desc "Track and manage many Git repositories from a single config"
  homepage "https://github.com/skaphos/repokeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repokeeper"

  # No zap stanza required

end
