# This file was generated by GoReleaser. DO NOT EDIT.
cask "sting" do
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/sting"]
    end
  end

  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "33d6ab4516fe2c9f870c6371be7eb00a6820c309a0ea4fd73b09f8e102ef29fd"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3bffa99042d1d3caf4cb2bcfdda44c9450f83b3eb26db8c0fe66e4ac449f5bcc"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2555f7729b0e8eac146bcad1de93e77a22556637c91c2cd43bfa3d19d2a972ce"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aadfee477a5fff8c4884b4432b3d1289b183893810df60fcaf352d2c5b5b4cc3"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sting"
  desc "Query a GitHub user's commits over a time window, as a CLI or MCP server"
  homepage "https://github.com/skaphos/sting"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sting"

  # No zap stanza required

end
