# This file was generated by GoReleaser. DO NOT EDIT.
cask "sting" do
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/sting"]
    end
  end

  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "c53ca146018a07ae1e5abd13810ae171f402e76521069659151236ee80595c8d"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc35bf135f1dcacad86280c27b70ec83a5a74023707f1aa779238ea22c56a42b"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84ce38a7a52dfcd2d0fc9fb2560a2811d21b70ae8a5b4848de8b6957deca2393"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1035fc401cb7484074975d61ea654c4d5f5733b797f9d8bf1e2e766f279b4907"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sting"
  desc "Query a GitHub user's commits over a time window, as a CLI or MCP server"
  homepage "https://github.com/skaphos/sting"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sting"

  # No zap stanza required
end
