# This file was generated by GoReleaser. DO NOT EDIT.
cask "sting" do
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/sting"]
    end
  end

  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "ff94895105542082060d175b2c58ba7751a81467203bb2a5b9ff62155c205d49"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "df3cfbf146ddd7fc44e9e9f4988a7f02c5ae67f1b246066f609248702dddde64"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4cc18c1c464301e9ff4c3b73ae6d48aebf18ddb00e27ce1e10fd72ab5ac0a898"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e33f0163afb920365baf53e5b5689d5003076fce89f4132d5db35ef59081363e"
      url "https://github.com/skaphos/sting/releases/download/v#{version}/sting_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sting"
  desc "Query a GitHub user's commits over a time window, as a CLI or MCP server"
  homepage "https://github.com/skaphos/sting"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sting"

  # No zap stanza required

end
