# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repokeeper < Formula
  desc "Track and manage many Git repositories from a single config"
  homepage "https://github.com/skaphos/repokeeper"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skaphos/repokeeper/releases/download/v0.0.1/repokeeper_0.0.1_darwin_amd64.tar.gz"
      sha256 "71bcd6c11503febaa406426acf57203456133a53778af0267d3a9e4730b103e0"

      def install
        bin.install "repokeeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skaphos/repokeeper/releases/download/v0.0.1/repokeeper_0.0.1_darwin_arm64.tar.gz"
      sha256 "b4eb49f25a0cfdb09e26fc25da7f3c9ed438d2b1cae17f0ee6b46c4cf24bdfc0"

      def install
        bin.install "repokeeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaphos/repokeeper/releases/download/v0.0.1/repokeeper_0.0.1_linux_amd64.tar.gz"
      sha256 "8d3c8c60722e3112f658022756b5c7e2a9cdc48fb6df625ab67612ac0e7f474e"
      def install
        bin.install "repokeeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skaphos/repokeeper/releases/download/v0.0.1/repokeeper_0.0.1_linux_arm64.tar.gz"
      sha256 "0b3b114945a2589456b94ad5292081067e2ddd98f8c6ddbf6df06b4372e421cc"
      def install
        bin.install "repokeeper"
      end
    end
  end

  test do
    system "#{bin}/repokeeper", "version"
  end
end
